# Generated by Django 6.0.6 on 2026-06-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_order_flw_transaction_id_order_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='product_stock_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='productsize_stock_gte_0'),
        ),
    ]
