# Generated by Django 6.0.6 on 2026-06-25 09:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_product_stock_quantity_alter_productsize_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label for this ad (not shown on site)', max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('header', models.CharField(help_text="e.g. 'Find the Boundaries. Push Through!'", max_length=255)),
                ('subheading', models.CharField(help_text="Short bold body — e.g. 'Shoes Sale on Gift Empire'", max_length=255)),
                ('teaser', models.CharField(blank=True, help_text="Short teaser — e.g. 'Starting At $119.99. Discounts last till April'", max_length=255)),
                ('cta_text', models.CharField(default='Shop Now', help_text="Button text — e.g. 'BUY NOW!'", max_length=100)),
                ('price_tag', models.CharField(blank=True, help_text="Optional price display — e.g. '$119.99'. Leave blank to hide.", max_length=50)),
                ('redirect_url', models.URLField(help_text='Where clicking the ad or CTA button takes the user')),
                ('is_active', models.BooleanField(default=False, help_text='Tick to make this the live banner. Only one can be active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Ad',
                'verbose_name_plural': 'Banner Ads',
                'ordering': ['-created_at'],
            },
        ),
    ]
