# Generated by Django 6.0.6 on 2026-06-25 09:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_bannerad'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label for this ad (not shown on site)', max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('header', models.CharField(max_length=255)),
                ('subheading', models.CharField(max_length=255)),
                ('teaser', models.CharField(blank=True, max_length=255)),
                ('cta_text', models.CharField(default='Shop Now', max_length=100)),
                ('price_tag', models.CharField(blank=True, max_length=50)),
                ('redirect_url', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Ad 2',
                'verbose_name_plural': 'Banner Ads 2',
                'ordering': ['-created_at'],
            },
        ),
    ]
